version: '3'
services:
  api:
    container_name: 'api'
    image: "${API_IMAGE_PATH}"
    ports:
        - '8080:8080'
    depends_on:
      - 'mongodb'
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
